spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: consumer
  kafka:
    # Адреса всех брокеров кластера
    bootstrap-servers:
      - http://localhost:29092
    listener:
      # Получение каждой записи должно быть подтверждено
      ack-mode: record
    producer:
      retries: 1
      client-id: ${spring.application.name}
      # Очередь для исключений
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.dtechs.consumer.kafka.config.serialization.DlqMessageSerializer
      transaction-id-prefix: ${spring.application.name}-${random.uuid}-
    consumer:
      group-id: ${spring.application.name}
      autoOffsetReset: earliest
      # Сериализаторы для всех типов
      keyDeserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      valueDeserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      # Транзакционность консьюмера
      isolation-level: read_committed
    properties:
      spring.json.value.default.type: io.dtechs.consumer.dto.MessageDto
      spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
      spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

kafka:
  topic:
    photos: photo
    videos: video
    text: text
    # dlq_ + <название топика>
    dlq-prefix: dlq_

storage:
  url: http://127.0.0.1:9000
  user: minioadmin
  password: minioadmin
  region: ru-central1
  bucket:
    photos: photo
    videos: video
    text: text
    # dlq- + <название топика>
    dlq-prefix: dlq-

server:
  port: 8081