version: '3.9'

services:

  minio:
    image: bitnami/minio:latest
    container_name: minio
    volumes:
      - minio-storage:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin

volumes:
  minio-storage:
    external: true