global:
#  scrape_timeout: 15s
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          group: 'prometheus'

  - job_name: 'kafka'
#    tls_config:
#      insecure_skip_verify: true
#    scrape_timeout: 10s
    static_configs:
      - targets: ['host.docker.internal:9308']
        labels:
          group: 'kafka'