global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          group: 'prometheus'

  - job_name: 'kafka'
    static_configs:
      - targets: ['host.docker.internal:9308']
        labels:
          group: 'kafka'