version: '3.9'

services:

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    expose:
      - "2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    restart: always
    ports:
      - "29092:29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    healthcheck:
      test: nc -z kafka 29092 || exit 1
      interval: 20s
      retries: 3
      start_period: 20s
      timeout: 20s

  kafka-ui:
    image: "provectuslabs/kafka-ui:latest"
    depends_on:
      - kafka
    container_name: kafka-ui
    ports:
      - "8090:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - AUTH_TYPE=LOGIN_FORM
      - SPRING_SECURITY_USER_NAME=dtechs
      - SPRING_SECURITY_USER_PASSWORD=dtechs
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    links:
      - kafka

  kafka-exporter:
    depends_on:
      - kafka
    image: danielqsj/kafka-exporter:latest
    container_name: kafka-exporter
    restart: always
    ports:
      - "9308:9308"
    command:
      - "--kafka.server=kafka:9092"
    links:
      - kafka

volumes:
  kafka_data:
    driver: local