{
 "title": "Kafka messages by topics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Unhandled messages by topics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_consumergroup_lag)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kafka\"}[$__rate_interval]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka messages by topics per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_topic_partition_current_offset{topic!~\"__consumer_offsets|__transaction_state\"}[$__rate_interval])) * 0.5",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}